feat: node builtins
eslint-community/eslint-plugin-n pull request #258
Opened 2024-04-29 08:37 UTC by aladdin-add

2024-04-29 08:42 UTC, aladdin-add commented
It may introduce new linting errors, which, according to eslint's versioning policy, I categorize as feat.

https://github.com/eslint/eslint?tab=readme-ov-file#semantic-versioning-policy

2024-04-29 14:54 UTC, scagood requested changes
I am not sure this is what we actually want to do 🤔

2024-04-29 14:54 UTC, scagood commented on lib/rules/no-unsupported-features/es-builtins.js
> -
I think these should remain here 👀

2024-04-29 14:54 UTC, scagood commented on lib/rules/no-unsupported-features/node-builtins.js
> +        // General APIs
I wanted to make a custom list from the node globals
https://nodejs.org/api/globals.html (via https://nodejs.org/api/globals.json)

As the numbers are quite different between mdn and the node docs 

If I find the time I will see if I can make a script to scrape that data, but so far I have found the scripts to be lacking 😅

2024-04-30 02:33 UTC, aladdin-add commented
it's to fix the issue: https://github.com/eslint-community/eslint-plugin-n/issues/260

2024-04-30 09:45 UTC, scagood approved these changes
I think this resolves #260 well

2024-04-30 09:47 UTC, merged

2024-04-30 09:52 UTC, aladdin-add commented
tips: it's recommended to use rebase, to help release-please generate better changelogs. :)

2024-04-30 10:06 UTC, scagood commented
As we're using squash merge, it actually makes no difference, as only the PR title is kept 👀

If we're using merge / rebase merge then 100% we'd need to worry :)

2024-04-30 10:17 UTC, aladdin-add commented
"node builtins" is repeated 2 times, and I'm not sure if it has anything to do with the use of merge:
https://github.com/eslint-community/eslint-plugin-n/blob/a70789a90c118f1ab69b8e1f5d4f1ac7f5dc3869/CHANGELOG.md#-features

2024-04-30 10:30 UTC, scagood commented
😱 that makes no sense. I guess I will steer clear for now!