feat: Add support for ignoring experemental features
eslint-community/eslint-plugin-n pull request #269
Opened 2024-05-08 11:39 UTC by scagood

closes #199

2024-05-08 11:54 UTC, scagood commented on lib/util/check-unsupported-builtins.js
> +            (options.allowExperimental === true && info.experimental != null)
I wonder if we should check the current range against the experimental range here so we don't allow experimental features that are not in the configured node version

2024-05-09 03:43 UTC, aladdin-add requested changes
can you update the rule docs, otherwise LGTM, thanks!

2024-05-09 11:44 UTC, aladdin-add commented on docs/rules/no-unsupported-features/node-builtins.md
> +The `"allowExperimental"` option accepts a boolean value
```suggestion
The `"allowExperimental"` option accepts a boolean value (the default value is `false`).
```

2024-05-10 06:26 UTC, aladdin-add approved these changes
LGTM, thanks!

2024-05-10 06:26 UTC, merged