fix: missing import recognise tsx extension
eslint-community/eslint-plugin-n pull request #97
Opened 2023-05-10 02:52 UTC by davidNHK

As a caption. 

When i try to import `tsx` file extension from file.

the `js` extension won't working

2023-05-10 02:58 UTC, aladdin-add requested changes
can you add the .idea/* to gitignore, otherwise LGTM, thanks!

2023-05-10 09:28 UTC, davidNHK commented
@aladdin-add updated according your comments.

Please check again :)

2023-05-10 11:45 UTC, merged

2023-05-10 11:53 UTC, aladdin-add commented
released in v16.0.0-1: https://github.com/eslint-community/eslint-plugin-n/releases/tag/16.0.0-1

please note it's a pre-release as I was preparing a major.

2023-09-01 06:42 UTC, jaydenseric reviewed
This isn't correct to map `.tsx` to `.jsx`, most TypeScript projects compile `.tsx` to `.js`. It depends on if the project TypeScript config has `jsx` configured to `"preserve"` or not:

- https://www.typescriptlang.org/docs/handbook/jsx.html#basic-usage
- https://www.typescriptlang.org/tsconfig#jsx

Edit: Sorry, I'm just now noticing there is an issue and PR about it: https://github.com/eslint-community/eslint-plugin-n/issues/108 https://github.com/eslint-community/eslint-plugin-n/pull/112

2023-09-01 09:03 UTC, aladdin-add commented
@jaydenseric can you please file a new issue to discuss it?

agreed it's not ideal to guess the actual tsconfig.  If we are not able to know it, I prefer not having the default - unless it was explicitly configured; while change it seems a breaking change. :)